#!/usr/bin/env python

import os
import time
import psutil
import subprocess
import sys

interface = "wlan1"
dump_dir = "/home/pi/dump"
os.chdir(dump_dir)
hash_file = "preview.txt"

def checkRoot():
    return os.geteuid() == 0

if not checkRoot():
    print("use root.")
    exit()

def get_adapters():
    addresses = psutil.net_if_addrs()
    stats = psutil.net_if_stats()
    ifs = []
    for intface, addr_list in addresses.items():
        ifs.append(intface)
    return ifs

def isRunning():
    return "hcxdumptool" in (p.name() for p in psutil.process_iter())

def noAdapter():
    ifs = get_adapters()
    for i in ifs:
        if i == interface:
            return False
    return True

def start_command(arg_list):
    process = subprocess.Popen(arg_list, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)
    output, _ = process.communicate()

def action_start():
    if isRunning():
        print("can't start, already running")
        return
    if noAdapter():
        print("can't start, no valid adapter")
        return

    bpf = os.path.join(os.path.dirname(os.path.realpath(__file__)), "hcx-menu-rpi-filter.bpf")
    print(f"bpf: {bpf}")
    print("starting...")
    start_command(['sudo', 'hcxdumptool', '-i', interface, f"--bpf={bpf}"])
    print("started.")

while True:
    action_start()
    time.sleep(2)
