#!/bin/bash

SEARCH="$1"
WRITE="$2"

if [ -z "$WRITE" ]; then
        hcx-info /media/SSD/root/dump/cap/all/apuniq.txt -s 5 | grep -i "$SEARCH"
else
        hcx-info /media/SSD/root/dump/cap/all/apuniq.txt -g "$SEARCH" >> fetch.txt
fi
